version: 2
jobs:
  build:
    docker:
      - image: bareit/pdflatex
    steps:
      - checkout
      - run:
          name: Start
          command: echo Compiling thesis.
      - run:
          name: Build
          command: bash build.sh
